# Generated by Django 4.1.1 on 2022-09-19 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_alter_order_options_alter_orderitems_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('percent_off', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('O', 'Открыт'), ('S', 'Подтверждён'), ('W', 'Ожидает'), ('C', 'Отменён')], default='O', max_length=1),
        ),
    ]
