# Generated by Django 4.1.1 on 2022-09-20 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_coupon_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='percent_off',
            field=models.FloatField(),
        ),
    ]
