# Generated by Django 4.1.1 on 2022-09-20 01:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_alter_coupon_percent_off'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='id',
            field=models.CharField(blank=True, max_length=255, primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='percent_off',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='скидка (в процентах)'),
        ),
        migrations.CreateModel(
            name='PromotionCode',
            fields=[
                ('id', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False, verbose_name='id')),
                ('code', models.CharField(blank=True, max_length=255, verbose_name='код')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.coupon', verbose_name='Купон')),
            ],
        ),
    ]
