# Generated by Django 4.1.1 on 2022-09-20 02:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_alter_coupon_id_alter_coupon_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False, verbose_name='id')),
                ('display_name', models.CharField(max_length=255, verbose_name='название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описапние')),
                ('inclusive', models.BooleanField()),
                ('percentage', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='проценты')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='promoution_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.promotioncode', verbose_name='промо-код'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('O', 'Открыт'), ('S', 'Подтверждён'), ('W', 'Ожидает'), ('C', 'Отменён')], default='O', max_length=1, verbose_name='статус'),
        ),
        migrations.AddField(
            model_name='order',
            name='taxes',
            field=models.ManyToManyField(to='items.tax', verbose_name='налоги'),
        ),
    ]
