# Generated by Django 4.1.1 on 2022-09-20 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_tax_order_promoution_code_alter_order_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='promoution_code',
            new_name='promotion_code',
        ),
    ]
